### ISSUE TITLE
abci.proto might be out of date, wrt TM 0.15.0

### ISSUE THREAD

**Issue by pdobacz** [KrzysiekJ/abci_server#2]
c.f. https://github.com/KrzysiekJ/abci_server/issues/1.

Since Tendermint 0.15.0 Leo, I cannot get tendemrint to talk to `abci_server` - Tendermint sends a `SetOption` request, and when I try to respons in my ABCI, it seems that it somehow expected a response to `Info`.

```
E[01-19|18:18:48.602] Stopping abci.socketClient for error: Unexpected result type *types.Response_SetOption when response to *types.Request_Info expected module=abci-client connection=query
```

Maybe the call that arrived at abci_server was a `RequestInfo` after all?

I tried updating the `abci.proto` myself, but was getting some errors.

**Comment by KrzysiekJ** [comment]
Updated ABCI to 0.9.0 (presumably used in Tendermint 0.15.0) in ee7e1674064. Let me know in case there are issues.
